# Site settings
title: アニメ「こうしす！」公式サイト
email: info-opap at opap.jp
description: 穴だらけ！？ 弊社自慢のセキュリティ――鉄道会社のIT部門を舞台にコメディで描く情報セキュリティ普及啓発アニメ「こうしす！」公式サイト。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kosys.opap.jp" # the base hostname & protocol for your site
enforce_ssl: kosys.opap.jp
twitter_username: kosys_pr
github_username:  opap-jp
repository: kosys/kosys.github.io
timezone: Asia/Tokyo

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
feed:
  path: atom.xml
gems:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - CNAME
  - README.md
  - Gemfile*
  - vendor
